import Head from "next/head";
import { Inter } from "next/font/google";
import "@/styles/Home.module.css";
import useSWR from "swr";
import { fetchFromURL } from "./_app";
import Link from "next/link";
import styled from "styled-components";

const StyledList = styled.ul`
  display: flex;
  flex-direction: column;
  gap: 10px;
  text-transform: capitalize;
  text-decoration: underline;
`;

type PokemonResult = {
  url: string;
  name: string;
};

type PokemonApiData = {
  count: number;
  next: string | null;
  previous: string | null;
  results: PokemonResult[];
};

export default function Home() {
  const { data, isLoading, error } = useSWR(
    "https://pokeapi.co/api/v2/pokemon",
    fetchFromURL<PokemonApiData>
  );
  if (isLoading) {
    return <h1>Loading...</h1>;
  }
  if (typeof data?.results === "undefined") {
    return <h1>{error.message}</h1>;
  }

  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledList>
        {data.results?.map((pokemon, index) => (
          <li key={pokemon.name}>
            <Link href={`${index + 1}`}>{pokemon.name}</Link>
          </li>
        ))}
      </StyledList>
    </>
  );
}
